version: "3"
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
     - "4444:4444"
    volumes:
    - ./var/selenium:/dev/shm

  php:
    build: docker/php
    volumes:
      - ./:/var/www
